import Head from "next/head";
import Image from "next/image";
import { ChangeEvent, useReducer, useState } from "react";
import styles from "../styles/Home.module.css";

interface Action {
  type: string;
  value: boolean;
}
interface State {
  "8chars": boolean;
  lowercase: boolean;
  uppercase: boolean;
  numbers: boolean;
  symbols: boolean;
}

const reducer = (state: State, action: Action) => {
  return { ...state, [action.type]: action.value };
};

export default function Home() {
  const [pass, setPass] = useState("");
  const [show, setShow] = useState(false);
  const [state, dispatch] = useReducer(reducer, {
    "8chars": false,
    lowercase: false,
    uppercase: false,
    numbers: false,
    symbols: false,
  });

  const HandlePasswordCheck = (e: ChangeEvent<HTMLInputElement>) => {
    const input = e.target.value;
    const patterns = {
      lowercase: new RegExp("(.*[a-z].*)"),
      uppercase: new RegExp("(.*[A-Z].*)"),
      numbers: new RegExp("[0-9]+"),
      symbols: /[`!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~]/,
    };
    setPass(input);

    if (!state["8chars"] && input.length >= 8)
      dispatch({ type: "8chars", value: true });
    else if (state["8chars"] && input.length < 8)
      dispatch({ type: "8chars", value: false });

    Object.entries(patterns).forEach(([item, value]) => {
      if (!state[item] && value.test(input))
        dispatch({ type: item, value: true });
      else if (state[item] && !value.test(input))
        dispatch({ type: item, value: false });
    });
  };

  const HandlePasswordToggle = () => setShow((prev) => !prev);

  return (
    <div>
      <Head>
        <title>Password Checker</title>
        <meta name="description" content="Generated by The Aman" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.formContainer}>
          <div className={styles.passwordContainer}>
            <input
              name="password"
              className={styles.passwordInput}
              placeholder="password"
              type={show ? "text" : "password"}
              onChange={HandlePasswordCheck}
            />
            <button
              className={styles.iconOnlyBtn}
              onClick={HandlePasswordToggle}
            >
              {!show ? (
                <svg
                  width="20px"
                  height="20px"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path d="M.2 10a11 11 0 0 1 19.6 0A11 11 0 0 1 .2 10zm9.8 4a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm0-2a2 2 0 1 1 0-4 2 2 0 0 1 0 4z" />
                </svg>
              ) : (
                <svg
                  width="20px"
                  height="20px"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path d="M12.81 4.36l-1.77 1.78a4 4 0 0 0-4.9 4.9l-2.76 2.75C2.06 12.79.96 11.49.2 10a11 11 0 0 1 12.6-5.64zm3.8 1.85c1.33 1 2.43 2.3 3.2 3.79a11 11 0 0 1-12.62 5.64l1.77-1.78a4 4 0 0 0 4.9-4.9l2.76-2.75zm-.25-3.99l1.42 1.42L3.64 17.78l-1.42-1.42L16.36 2.22z" />
                </svg>
              )}
            </button>
          </div>
          <div className={styles.passwordChecker}>
            <ul>
              <p>Your password must contain:</p>
              <li data-matched={state["8chars"]}>At least 8 characters</li>
              <li data-matched={state["lowercase"]}>Lower case letters(a-z)</li>
              <li data-matched={state["uppercase"]}>Upper case letters(A-Z)</li>
              <li data-matched={state["symbols"]}>Symbols(@, $, #)</li>
              <li data-matched={state["numbers"]}>Numbers(0-9)</li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  );
}
